### ISSUE TITLE
Another Rust impostor game

### ISSUE THREAD

**Issue by erlend-sh** [bschwind/sus#2]
Are you aware of Airlock? https://github.com/rictic/airlock.chat

They’ve come pretty far already. Maybe you could collaborate?

**Comment by bschwind** [comment]
Hi @erlend-sh ! I hadn't come across that before. I took a look through the code, they've definitely made a lot of progress. I'm treating this project more as a learning experience to get familiar with wgpu and laminar because I have some future game ideas I'd like to make in Rust and I want to iron out the dev approach I would take. This seemed like an easy project to get familiar with things.

Thanks for bringing them to my attention though, I'll try building and playing it :)
